#ifndef _h_EmTcpBase
#define _h_EmTcpBase

#define EM_TCP_CMD_RAW 0
#define EM_TCP_CMD_BEAT 1
#define EM_TCP_CMD_CLOSE 2
#define EM_TCP_CMD_TEXT 3
#define EM_TCP_CMD_FILE 4

#define EM_TCP_CMD_RAW_STR "raw"
#define EM_TCP_CMD_BEAT_STR "beat"
#define EM_TCP_CMD_CLOSE_STR "close"
#define EM_TCP_CMD_TEXT_STR "text"
#define EM_TCP_CMD_FILE_STR "file"

#define EM_TCP_SIDE_SERVER 1
#define EM_TCP_SIDE_CLIENT 2


#define EM_TCP_PACK_PAD_STR ","
#define EM_TCP_PACK_BEGIN_STR "<<<<<<<<<<"
#define EM_TCP_PACK_END_STR ">>>>>>>>>>"
#define EM_TCP_PACK_SECTION_SIZE 20
#define EM_TCP_PACK_SECTION_COUNT 5
#define EM_TCP_PACK_BOUND_SIZE 10
#define EM_TCP_PACK_MIN_SIZE 120
#define EM_TCP_PACK_HEAD_SIZE 110
#define EM_TCP_PACK_FILE_META_SIZE 1000
#define EM_TCP_PACK_READER_BUF_SIZE 1024*1024

#define EM_TCP_ACTION_DEFAULT 0
#define EM_TCP_ACTION_RECEIVE_NEXT 1
#define EM_TCP_ACTION_CONNECTION_CLOSE 2
#define EM_TCP_ACTION_ACCEPT_NEXT 3
#define EM_TCP_ACTION_ACCEPT_CONTINUE 4
#define EM_TCP_ACTION_ACCEPT_DROP 5

#define EM_TCP_DEFAULT_SEND_FILE_SLEEP 600
#define EM_TCP_DEFAULT_SEND_BUF_SIZE 1024*1024
#define EM_TCP_DEFAULT_SEND_MAX_IDLE 2*1000
#define EM_TCP_DEFAULT_SEND_TIMEOUT 1*1000
#define EM_TCP_DEFAULT_SEND_MAX_FAIL 5
#define EM_TCP_DEFAULT_RECV_BUF_SIZE 1024*1024
#define EM_TCP_DEFAULT_RECV_MAX_IDLE 5*1000
#define EM_TCP_DEFAULT_RECV_TIMEOUT 1*1000
#define EM_TCP_DEFAULT_ACCEPT_TIMEOUT 1*1000
#define EM_TCP_DEFAULT_ACCEPT_MAX_IDLE 24*60*60*1000


#define EM_TCP_TEMP_FILE_EXT_STR ".tmp"
#define EM_TCP_CHARSET_STR "utf-8"

#ifndef SOCKET 
typedef unsigned int SOCKET;
#endif

#ifndef INVALID_SOCKET
#define INVALID_SOCKET (SOCKET)(~0)
#endif

#include <afx.h>

#endif