//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FirmwareModifier.rc
//
#define IDS_TAB_TITLE_EN                1
#define IDS_TAB_TITLE_CH                2
#define IDS_TOP_LEFT_EN                 3
#define IDS_TOP_LEFT_CH                 4
#define IDS_TOP_RIGHT_EN                5
#define IDS_TOP_RIGHT_CH                6
#define IDS_BOTTOM_LEFT_EN              7
#define IDS_BOTTOM_LEFT_CH              8
#define IDS_BOTTOM_RIGHT_EN             9
#define IDS_BOTTOM_RIGHT_CH             10
#define IDS_GET_DIR_EN                  11
#define IDS_GET_DIR_CH                  12
#define IDD_DIALOG_NOTE_PAD             103
#define IDD_DIALOG_TEST_PLATFORM        1100
#define IDR_MENU_APKS                   1102
#define IDR_MENULIST                    1102
#define IDD_CHARGE_IMAGE                1105
#define IDD_DIALOG_BATTERY_PARAM        1106
#define IDC_BUTTON_TOP_RIGHT            1201
#define IDC_BUTTON_TOP_LEFT             1202
#define IDC_BUTTON_BOTTOM_LEFT          1203
#define IDC_BUTTON_BOTTOM_RIGHT         1204
#define IDC_BUTTON_GET_DIR              1205
#define IDC_BUTTON_READ_BATTERY         1205
#define IDC_BUTTON_WRITE_BATTERY        1206
#define IDC_SYS_EDIT2                   1206
#define IDC_RADIO_CELL_ONE              1207
#define IDC_SYS_EDIT5                   1207
#define IDC_RADIO_CELL_TWO              1208
#define IDC_SYS_EDIT4                   1208
#define IDC_EDIT_PULL_UP                1209
#define IDC_SYS_EDIT6                   1209
#define IDC_EDIT_PULL_DOWN              1210
#define IDC_SYS_EDIT7                   1210
#define IDC_GROUP_CELL                  1211
#define IDC_STATIC_PULL_UP              1212
#define IDC_SYS_EDIT3                   1212
#define IDC_STATIC_PULL_DOWN            1213
#define IDC_EDIT_DISCHARGE_1            1214
#define IDC_EDIT_DISCHARGE_2            1215
#define IDC_SYS_EDIT1                   1215
#define IDC_EDIT_DISCHARGE_3            1216
#define IDC_BTN_CONFIRM_MODIFY          1217
#define IDC_EDIT_DISCHARGE_4            1217
#define BTN_REPLACE_BOOT_LOGO           1218
#define IDC_EDIT_DISCHARGE_5            1218
#define BTN_REPLACE_BOOT_ANIMATION      1219
#define IDC_EDIT_DISCHARGE_6            1219
#define BTN_REPLACE_DEFAULT_WALLPAPER   1220
#define IDC_EDIT_DISCHARGE_7            1220
#define IDC_EDIT_DISCHARGE_8            1221
#define BTN_REPLACE_SHUTDOWN_ANIMATION  1221
#define IDC_EDIT_DISCHARGE_9            1222
#define IDC_EDIT_DISCHARGE_10           1223
#define IDC_EDIT_DISCHARGE_11           1224
#define IDC_GROUP_DISCHARGE             1225
#define IDC_GROUP_CHARGE                1226
#define BTN_REPLACE_KERNEL_LOGO         1226
#define IDC_EDIT_CHARGE_1               1227
#define BTN_REPLACE_CHARGE_LOGO         1228
#define IDC_EDIT_CHARGE_2               1228
#define IDC_EDIT_CHARGE_3               1229
#define IDC_EDIT_CHARGE_4               1230
#define IDC_EDIT_CHARGE_5               1231
#define IDC_COMBO7                      1231
#define IDC_STATIC1                     1232
#define IDC_EDIT_CHARGE_6               1232
#define IDC_STATIC2                     1233
#define IDC_EDIT_CHARGE_7               1233
#define IDC_STATIC3                     1234
#define IDC_EDIT_CHARGE_8               1234
#define IDC_STATIC4                     1235
#define IDC_EDIT_CHARGE_9               1235
#define IDC_EDIT_CHARGE_10              1236
#define IDC_EDIT_CHARGE_11              1237
#define IDC_STATIC7                     1238
#define IDC_BTN_READ_BATTERY_DATA       1238
#define IDC_STATIC8                     1239
#define IDC_STATIC9                     1240
#define IDC_TAB2                        1248
#define IDC_TAB_APK                     1248
#define IDC_TAB_APKS                    1248
#define IDC_BTN_MODIFY_BUILD_PROP       1249
#define IDC_BTN_MODIFY_KEY_MAP          1250
#define IDC_BTN_MODIFY_SYS_CONFIG       1251
#define IDC_TAB_LOGO                    1252
#define IDC_STATIC_LOGO_CONFIG          1253
#define IDC_BUTTON10                    1254
#define IDC_STATIC_LOGO                 1254
#define IDC_STATIC_SYS_INFO             1255
#define IDC_STATIC_USB_CONFIG           1256
#define IDC_STATIC_SYS_SETTINGS         1257
#define IDC_STATIC_SYS_SETTINGS_BACKUP  1258
#define IDC_STATIC_APKS_CONFIG          1259
#define IDC_BTN_MODIFY_BATTERY_PARAM    1260
#define IDC_BTN_CLONE                   1261
#define BTN_REPLACE_BOOT_RING           1262
#define IDC_BTN_MODIFY_KERNEL_PARAMETER 1263
#define IDC_LIST_SYS_APKS               1264
#define IDC_LIST_PREINST_APKS           1265
#define BTN_REPLACE_SHUTDOWN_RING       1266
#define IDC_EDIT                        1267
#define IDC_BTN_CLOSE                   1268
#define IDC_STATIC_PIXEL_INFO           1269
#define IDC_BATTERY_IMAGE0              1270
#define IDC_STATIC_PIXEL_MAX_INFO       1270
#define IDC_STATIC_PIXEL_INFO2          1270
#define IDC_BATTERY_IMAGE1              1271
#define IDC_BATTERY_IMAGE2              1272
#define IDC_BATTERY_IMAGE3              1273
#define IDC_BATTERY_IMAGE4              1274
#define IDC_STATIC_CHARGE               1274
#define IDC_LIST_PREINST_DEL_APKS       1274
#define IDC_BATTERY_IMAGE5              1275
#define IDC_STATIC_VERSION              1275
#define IDC_BATTERY_IMAGE6              1276
#define IDC_EDIT1                       1276
#define IDC_BATTERY_IMAGE7              1277
#define IDC_RADIO1                      1278
#define IDC_RADIO2                      1279
#define IDC_STATIC_CHARGE_DIS           1280
#define IDC_STATIC0                     1281
#define IDC_STATIC5                     1282
#define IDC_STATIC6                     1283
#define IDC_STATIC20                    1285
#define IDC_STATIC21                    1286
#define IDC_STATIC22                    1287
#define IDC_STATIC23                    1288
#define IDC_STATIC24                    1289
#define IDC_STATIC25                    1290
#define IDC_STATIC26                    1291
#define IDC_STATIC27                    1292
#define IDC_BUTTON1                     1293
#define IDC_BUTTON20                    1293
#define IDC_BUTTON2                     1294
#define IDC_BUTTON21                    1294
#define IDC_BUTTON3                     1295
#define IDC_BUTTON22                    1295
#define IDC_BUTTON4                     1296
#define IDC_BUTTON23                    1296
#define IDC_BUTTON5                     1297
#define IDC_BUTTON24                    1297
#define IDC_BUTTON6                     1298
#define IDC_BUTTON25                    1298
#define IDC_BUTTON7                     1299
#define IDC_BUTTON26                    1299
#define IDC_BUTTON8                     1300
#define IDC_BUTTON27                    1300
#define IDC_PROGRESS_CLONE              1301
#define IDC_STATIC_BOOT_RING            1302
#define IDC_EDIT_BOOT_RING_PATH         1303
#define IDC_CHECK_ENABLE_BT             1304
#define IDC_EDIT_CLONE_INTRO            1305
#define IDC_CHECK_ENABLE_BT2            1306
#define IDC_CHECK_WAPE_USER             1306
#define IDC_STATIC_SHUTDOWN_RING        1307
#define IDC_EDIT_SHUTDOWN_RING_PATH     1308
#define POPMENU_ADD                     32771
#define POPMENU_DEL                     32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1109
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1291
#define _APS_NEXT_SYMED_VALUE           1101
#endif
#endif
